aws.s3.region=us-east-2
aws.s3.bucket=bucket-class1-208367987388-us-east-2-an

aws.dynamodb.region=us-east-2
aws.dynamodb.table=table-class1

aws.sns.region=us-east-2
aws.sns.topic.arn=arn:aws:sns:us-east-2:208367987388:aws-class1


aws.sqs.region=us-east-2
aws.sqs.url=https://sqs.us-east-2.amazonaws.com/208367987388/quere-aws-class1